### ISSUE TITLE
datasets download

### ISSUE THREAD

**Issue by KN-Zhang** [mapillary/mapillary_sls#20] opened 2021-10-05 07:14 UTC
Hello~ When I try to download the mapillary dataset, it always informs “Error submitting request, please try again”. Maybe the requested full name I input is wrong? Or anything else?

**Comment by mlopezantequera** [comment] 2021-10-05 07:16
It could be related to recent outages in the Facebook networks, can you try again in a few hours ?

**Comment by KN-Zhang** [comment] 2021-10-05 07:27
> It could be related to recent outages in the Facebook networks, can you try again in a few hours ?

Thanks. I also wanna know is there any limitation for the required full name in the download page? Or I could fill the box whatever I like?

**Comment by mlopezantequera** [comment] 2021-12-29 09:39
@KN-Zhang not sure if there is any limitations in terms of character sets or length. Did you manage to download the data?

**Comment by KLYSxc616** [comment] 2022-01-11 09:22
Stop every time the download reaches 1G ，I cry. Do you know what's the reason, I need your help

**Comment by KLYSxc616** [comment] 2022-01-11 09:24
Stop every time the download reaches 1G ，I cry. Do you know what's the reason, I need your help

**Comment by mlopezantequera** [comment] 2022-01-11 09:25
We are working on fixing the issues related with the download, sadly I can't provide a short-term workaround but I will update here once it's resolved

**Comment by KLYSxc616** [comment] 2022-01-11 09:58
Thanks bro every much,  I just lack the datasets now. My network has already finished.



---- 回复的原邮件 ----
| 发件人 | Manuel López ***@***.***> |
| 日期 | 2022年01月11日 17:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [mapillary/mapillary_sls] datasets download (#20) |

We are working on fixing the issues related with the download, sadly I can't provide a short-term workaround but I will update here once it's resolved

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mlopezantequera** [comment] 2022-02-14 10:49
@KN-Zhang , @KLYSxc616 , it seems the problem is resolved and downloads should now work. I am closing this, do re-open if the problem persists. Thanks for your patience

**Closed as completed by mlopezantequera** 2022-02-14 10:49 UTC
