### ISSUE TITLE
fail downloading msls_images_vol_[1|2|3|4|5].zip

### ISSUE THREAD

**Issue by ramdrop** [mapillary/mapillary_sls#23] opened 2022-01-12 18:12 UTC
Hi, I am trying to download the MSLS dataset from https://www.mapillary.com/dataset/places, and I successfully downloaded
- msls_checksums.md5 
- msls_images_vol_6.zip 
- msls_metadata.zip 
- msls_patch_v1.1.zip 

while I failed downloading
- msls_images_vol_[1|2|3|4|5].zip

for example, specifically, after clicking msls_images_vol_1.zip, the broswer would bring me to a new page, then just stucked there:
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/73425467/149197544-6059c8de-8e4b-41b4-819b-e99d15af03ed.png">

(I am using Firefox with incognito tabs)

**Comment by mlopezantequera** [comment] 2022-01-14 10:21
Hi @ramdrop , we're aware of this and working on solving it. Will reply in this issue to ask you to try again when it's ready.

Thanks for your patience

**Comment by WHBSmith** [comment] 2022-01-23 14:30
I am also unable to download the dataset! Just wondering if there was a timeline for when this might be solved?

**Comment by bchidlovskii** [comment] 2022-01-27 15:25
We are also inpatient to know when the links will be updated. Thank you

**Comment by mlopezantequera** [comment] 2022-02-14 10:49
@ramdrop , @bchidlovskii , @WHBSmith , it seems the problem is resolved and downloads should now work. I am closing this, do re-open if the problem persists. Thanks for your patience

**Closed as completed by mlopezantequera** 2022-02-14 10:49 UTC
